### ISSUE TITLE
点击弹框里面的协议，查看协议；再次返回后，弹框消失。

### ISSUE THREAD

**Issue by An-001** [DoctorWei/mp-privacy#1]
1、当进入页面触发了 getPhoneNumber 隐私接口，弹框出现。
2、点击弹框的隐私协议，进入小程序官方的隐私页面；
3、手动返回，页面的弹框消失了，也出不来了。

不知道是我代码的问题，还是其他什么问题呢？

**Comment by An-001** [comment]
把 pageLifetimes 里的 hide方法删了就行了。

**Comment by DoctorWei** [comment]
已修复此bug，请使用最新版本测试

**Comment by An-001** [comment]
弹框出现，锁屏后。再次打开也是不行。

**Comment by DoctorWei** [comment]
未能复现问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 上午10:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [DoctorWei/mp-privacy] 点击弹框里面的协议，查看协议；再次返回后，弹框消失。 (Issue #1)




 
弹框出现，锁屏后。再次打开也是不行。
